name: Build, test and release

on:
  push:
    branches: [ master, setup-extension ]
    paths:
      - 'src/**'
#      - '*.xml'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Integration Test
        run: mvn failsafe:integration-test failsafe:verify