name: release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version for the release."
        required: true
        default: "X.Y.Z"

jobs:

  release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Build .jar
        run: mvn -B package -DskipTests --file pom.xml
      - name: Release to GitHub releases
        uses: softprops/action-gh-release@v2
        with:
          files: "target/keycloak-registered-user-to-group.jar"
          fail_on_unmatched_files: true
          tag_name: v${{ github.event.inputs.releaseVersion }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"