name: release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version for the release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Next default version."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Validate Versions
        run: |
          echo "Release Version: ${{ github.event.inputs.releaseVersion }}"
          echo "Development Version: ${{ github.event.inputs.developmentVersion }}"
#      - name: Release Maven artifacts
#        run: |
#          mvn -B clean release:prepare release:perform \
#            -s maven-settings.xml \
#            -DpushChanges=false \
#            -DlocalCheckout=true \
#            -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
#            -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
#          git push origin v${{ github.event.inputs.releaseVersion }}
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#      - name: Release to GitHub releases
#        uses: softprops/action-gh-release@v2
#        with:
#          files: "target/keycloak-registered-user-to-group.jar"
#          fail_on_unmatched_files: true
#          tag_name: v${{ github.event.inputs.releaseVersion }}
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"